name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    # don't run on pushes to forks
    if: github.event_name == 'pull_request' || github.repository == 'harvard-lil/LeftToRight'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      ### run tests ###
      - name: pytest
        run: |
          set -x
          pip install poetry
          poetry run pip install --upgrade pip
          poetry install
          poetry run pytest
